# Etapa 1: Build
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /app

# Restaurar dependencias
COPY *.csproj ./
RUN dotnet restore

# Copiar todo el proyecto
COPY . ./

# Publicar en Release
RUN dotnet publish -c Release -o /app/publish

# Etapa 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app

# Copiar la app publicada
COPY --from=build /app/publish ./

# Configurar puerto dinámico para Render
ENV ASPNETCORE_URLS=http://+:$PORT

# Exponer puerto dinámico
EXPOSE $PORT

# Ejecutar la API
ENTRYPOINT ["dotnet", "HelldiversApi.dll"]
